"""add job source_dir and output_files

Revision ID: 9b12e31396d0
Revises: 915b67a28f25
Create Date: 2026-06-06 13:47:57.905787

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b12e31396d0"
down_revision: str | Sequence[str] | None = "915b67a28f25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("source_dir", sa.String(length=500), server_default="", nullable=False)
        )
        batch_op.add_column(sa.Column("output_files", sa.Text(), server_default="", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("output_files")
        batch_op.drop_column("source_dir")

    # ### end Alembic commands ###
